# Generated by Django 4.2.4 on 2023-09-12 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=2000)),
                ('prix', models.CharField(max_length=200)),
                ('classe', models.CharField(blank=True, choices=[('SIL', 'SIL'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1'), ('Tle', 'Tle'), ('From 1', 'From 1'), ('From 2', 'From 2'), ('From 3', 'From 3'), ('From 4', 'From 4'), ('From 5', 'From 5'), ('From 6', 'From 6'), ('From 7', 'From 7'), ('Aucun', 'Aucun')], max_length=2000)),
                ('serie', models.CharField(blank=True, choices=[('C', 'C'), ('D', 'D'), ('E', 'E'), ('Ti', 'Ti'), ('Chinois', 'Chinois'), ('All/Esp', 'All/Esp'), ('Esp', 'Esp'), ('Aucun', 'Aucun')], max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='manuels')),
                ('francophone', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255)),
                ('residence', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('developpeur', models.BooleanField(default=False)),
                ('testeur', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.article')),
                ('contenu_paquet', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name': 'Accessoire',
                'verbose_name_plural': 'Accessoires',
            },
            bases=('core.article',),
        ),
        migrations.CreateModel(
            name='Cahiers',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.article')),
                ('nbre_page', models.CharField(max_length=2000)),
                ('contenu_paquet', models.CharField(blank=True, max_length=2000)),
                ('cartonne', models.BooleanField(default=False)),
            ],
            bases=('core.article',),
        ),
        migrations.CreateModel(
            name='LivrePrimaire',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.article')),
                ('matiere', models.CharField(choices=[('Mathematiques', 'Mathematiques'), ('Langage', 'Langage'), ('Dessin-peinture-coloriage', 'Dessin-peinture-coloriage'), ('TIC', 'TIC'), ('Sciences et Technologies', 'Sciences et Technologies'), ('Sciences à la citoyenneté', 'Sciences à la citoyenneté'), ('Français', 'Français'), ('Ecriture', 'Ecriture'), ('Anglais', 'Anglais'), ('Sciences Humaines et Sociales', 'Sciences Humaines et Sociales'), ('Litterature', 'Litterature')], max_length=2000)),
                ('editeur', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name': 'LivrePrimaire',
                'verbose_name_plural': 'LivrePrimaires',
            },
            bases=('core.article',),
        ),
        migrations.CreateModel(
            name='LivreSecondaire',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.article')),
                ('matiere', models.CharField(choices=[('Langue Française', 'Langue Française'), ('Litterature', 'Litterature'), ('Anglais', 'Anglais'), ('Histoire', 'Histoire'), ('Geographie', 'Geographie'), ('Education à la citoyenneté', 'Education à la citoyenneté'), ('Langue et culture nationale', 'Langue et culture nationale'), ('Art', 'Art'), ('Mathematiques', 'Mathematiques'), ('Sciences', 'Sciences'), ('Informatique', 'Informatique'), ('Latin', 'Latin'), ('Langues Etrangère', 'Langues Etrangère'), ('SVT', 'SVT'), ('PCT', 'PCT'), ('Philosophie', 'Philosophie'), ('Physique', 'Physique'), ('Chimie', 'Chimie'), ('Arts cinematographiques', 'Arts cinematographiques'), ('Sciences Tles Litteraires', 'Sciences Tles Litteraires')], max_length=2000)),
                ('auteur', models.CharField(blank=True, max_length=2000)),
                ('editeur', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name': 'LivreSecondaire',
                'verbose_name_plural': 'LivreSecondaires',
            },
            bases=('core.article',),
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix', models.CharField(max_length=255)),
                ('envoye_commande', models.BooleanField(default=False)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste', models.CharField(blank=True, max_length=2000000)),
                ('date_commande', models.DateTimeField()),
                ('montant', models.CharField(max_length=255)),
                ('livré', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
    ]
