# Generated by Django 4.2.4 on 2023-08-17 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=2000)),
                ('nom', models.CharField(blank=True, max_length=2000)),
                ('editeur', models.CharField(blank=True, max_length=2000)),
                ('prix', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='manuels')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact_1', models.CharField(blank=True, max_length=30)),
                ('contact_2', models.CharField(max_length=30)),
                ('residence', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('C', 'C'), ('D', 'D'), ('E', 'E'), ('Ti', 'Ti'), ('Chinois', 'Chinois'), ('All/Esp', 'All/Esp')], max_length=255)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('SIL', 'SIL'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('Tle', 'Tle'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1'), ('Tle', 'Tle')], max_length=255)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('prix', models.CharField(max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
