# Generated by Django 4.2.4 on 2023-08-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='article',
            name='matiere',
            field=models.CharField(choices=[('Langue Française', 'Langue Française'), ('Litterature', 'Litterature'), ('Anglais', 'Anglais'), ('Histoire', 'Histoire'), ('Geographie', 'Geographie'), ('Education à la citoyenneté', 'Education à la citoyenneté'), ('Langue et culture nationale', 'Langue et culture nationale'), ('Art', 'Art'), ('Mathematiques', 'Mathematiques'), ('Sciences', 'Sciences'), ('Informatique', 'Informatique'), ('Lantin', 'Lantin'), ('Langues Etrangère', 'Langues Etrangère'), ('SVT', 'SVT'), ('PCT', 'PCT'), ('Philosophie', 'Philosophie'), ('Physique', 'Physique'), ('Chimie', 'Chimie'), ('Arts cinematographiques', 'Arts cinematographiques'), ('Sciences Tles Litteraires', 'Sciences Tles Litteraires')], max_length=2000),
        ),
    ]
