# Generated by Django 4.2.4 on 2023-09-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_contenu_paquet_cahiers_contenu_paquets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cahiers',
            options={'verbose_name': 'Cahiers', 'verbose_name_plural': 'Cahiers'},
        ),
        migrations.RenameField(
            model_name='accessoire',
            old_name='contenu_paquet',
            new_name='contenu_paquets',
        ),
    ]
