# Generated by Django 4.2.4 on 2023-08-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_auteur_alter_article_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='niveau',
            field=models.CharField(blank=True, choices=[('SIL', 'SIL'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1'), ('Tle', 'Tle')], max_length=2000),
        ),
        migrations.AddField(
            model_name='article',
            name='serie',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('D', 'D'), ('E', 'E'), ('Ti', 'Ti'), ('Chinois', 'Chinois'), ('All/Esp', 'All/Esp')], max_length=2000),
        ),
        migrations.DeleteModel(
            name='Niveau',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
