# Generated by Django 4.2.4 on 2023-08-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_1',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_2',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
