# Generated by Django 4.2.4 on 2023-08-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_contact_1_alter_user_contact_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_livraison',
        ),
    ]
