# Generated by Django 4.2.4 on 2023-08-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_commande_date_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='status',
            field=models.CharField(blank=True, choices=[('En Cours', 'En Cours'), ('Livré', 'Livré')], default='En Cours', max_length=255),
        ),
    ]
