# Generated by Django 4.2.4 on 2023-08-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_panier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='status',
            field=models.CharField(choices=[('En Cours', 'En Cours'), ('Livré', 'Livré')], default='En Cours', max_length=255),
        ),
    ]
