# Generated by Django 4.2.4 on 2023-08-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_panier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='status',
            field=models.CharField(choices=[('En Cours', 'En Cours'), ('Ajouté', 'Ajouté')], default='En Cours', max_length=255),
        ),
    ]
